services:

  next-launcher-core:
    image: 'proteomicscnic/next-launcher-core:0.1.0'
    ports:
      - "8080:8080"
    environment:
      - PORT_CORE=$PORT_CORE
      - PORT_APP=$PORT_APP
      - HOST_IP=$HOST_IP
    volumes:
      - workspace:/workspace
    networks:
      - app-network
    command: [ "sh", "-c", "cd ${NXF_API_HOME} && ./scripts/startup-local.sh file" ]

  next-launcher-app:
    image: 'proteomicscnic/next-launcher-app:0.1.0'
    ports:
      - "3000:3000"
    environment:
      - PORT_CORE=$PORT_CORE
      - PORT_APP=$PORT_APP
      - HOST_IP=$HOST_IP
    volumes:
      - workspace:/workspace
    networks:
      - app-network
    command: [ "sh", "-c", "cd ${NEXTLAUNCHER_HOME}/app && npm start" ]


volumes:

  workspace:
    name: 'workspace'
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:\\next-Launcher\\production'


networks:

  app-network:

