services:

  next-launcher-core:
    image: 'proteomicscnic/next-launcher-core:1.0.0'
    ports:
      - "8080:8080"
    environment:
      - HOST_IP=$HOST_IP
    volumes:
      - workspace:/workspace
    networks:
      - app-network

  next-launcher-app:
    image: 'proteomicscnic/next-launcher-app:1.0.0'
    ports:
      - "3000:3000"
    volumes:
      - workspace:/workspace
    networks:
      - app-network


volumes:

  workspace:
    name: 'workspace'
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:\\next-Launcher\\production'


networks:

  app-network:

