services:

  next-launcher-core:
    image: 'proteomicscnic/next-launcher-core:1.0.1'
    ports:
      - "8082:8080"
    volumes:
      - workspace:/workspace
      - databuild:/databuild
    networks:
      - app-network

  next-launcher-app:
    image: 'proteomicscnic/next-launcher-app:1.0.1'
    ports:
      - "3002:3000"
    volumes:
      - workspace:/workspace
    networks:
      - app-network


volumes:

  workspace:
    name: 'workspace2'
    driver: 'local'
    driver_opts:
      type: 'cifs'
      o: 'addr=tierra.cnic.es,domain=CNIC,username=jmrodriguezc,password=JaDe20-34!;'
      device: '\\tierra.cnic.es\sc\U_Proteomica\UNIDAD\DatosCrudos\next-Launcher\'

  databuild:
    name: 'databuild'


networks:

  app-network:

