services:

  next-launcher-db:
    image: 'proteomicscnic/next-launcher-db:$NL_DB_VERSION'
    container_name: 'next-launcher-db'
    environment:
      # mongodb
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PWD
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - "nl_db:/data/db" # mount data folder
    networks:
      - next-launcher-network
    command: [ "mongod" ]

  next-launcher-core:
    image: 'proteomicscnic/next-launcher-core:$NL_VERSION'
    container_name: 'next-launcher-core'
    depends_on:
      - next-launcher-db
    environment:
      # mongodb
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PWD=$MONGODB_PWD
      - MONGODB_DB=$MONGODB_DB
      # servers
      - PORT_CORE=$PORT_CORE
      - PORT_APP=$PORT_APP
      - HOST_IP=$HOST_IP
      # nextflow-api
      - USER_GUEST=$USER_GUEST
      - PWD_GUEST=$PWD_GUEST
      - USER_ADMIN=$USER_ADMIN
      - PWD_ADMIN=$PWD_ADMIN
      # workspace
      - WORKSPACE_HOME=${WORKSPACE_HOME}
      # outspace
      - OUTSPACE_HOME=${OUTSPACE_HOME}
      # shared volumes
      - SHARED_VOLUMES=$SHARED_VOLUMES
    ports:
      - "${PORT_CORE}:${PORT_CORE}"
    volumes:
      - "nl_conf:/opt/nextflow/conf" # mount folder for nextflow config
      - "nl_workspace:${WORKSPACE_HOME}"
      - "nl_outspace:${OUTSPACE_HOME}"
      - "${SHARED_VOLUME_1}"
    networks:
      - next-launcher-network
    command: [ "sh", "-c", "/opt/nextflow-api/scripts/startup-local.sh mongo" ]

  next-launcher-app:
    image: 'proteomicscnic/next-launcher-app:$NL_VERSION'
    container_name: 'next-launcher-app'
    environment:
      # servers
      - PORT_CORE=$PORT_CORE
      - PORT_APP=$PORT_APP
      - HOST_IP=$HOST_IP
      # workspace
      - WORKSPACE_HOME=${WORKSPACE_HOME}
      # outspace
      - OUTSPACE_HOME=${OUTSPACE_HOME}
      # shared volumes
      - SHARED_VOLUMES=$SHARED_VOLUMES
    ports:
      - "${PORT_APP}:${PORT_APP}"
    volumes:
      - "nl_pipelines:/opt/next-launcher-app/app/public/pipelines" # mount folder with the pipeline schemas
      - "nl_workspace:${WORKSPACE_HOME}"
      - "nl_outspace:${OUTSPACE_HOME}"
      - "${SHARED_VOLUME_1}"
    networks:
      - next-launcher-network
    command: [ "sh", "-c", "cd /opt/next-launcher-app/app && PORT=$PORT_APP  REACT_APP_HOST_IP=$HOST_IP  REACT_APP_PORT_CORE=$PORT_CORE  npm start" ]



volumes:

  nl_db:
    name: 'nl_db'
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend/db'

  nl_conf:
    name: 'nl_conf'
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend/nextflow/conf'

  nl_pipelines:
    name: 'nl_pipelines'
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './frontend/pipelines'

  nl_workspace:
    name: 'nl_workspace'
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './workspace'

  nl_outspace:
    name: 'nl_outspace'
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './workspace'

  c:
    name: 'c'
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:\\'



networks:

  next-launcher-network:
