services:

  next-launcher-db:
    image: 'proteomicscnic/next-launcher-db:$NL_VERSION'
    container_name: 'next-launcher-db'
    environment:
      # mongodb
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PWD
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    networks:
      - next-launcher-network
    command: [ "mongod" ]

  next-launcher-core:
    image: 'proteomicscnic/next-launcher-core:$NL_VERSION'
    container_name: 'next-launcher-core'
    depends_on:
      - next-launcher-db
    environment:
      # mongodb
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PWD=$MONGODB_PWD
      - MONGODB_DB=$MONGODB_DB
      # servers
      - PORT_CORE=$PORT_CORE
      - PORT_APP=$PORT_APP
      - HOST_IP=$HOST_IP
      # nextflow-api
      - USER_GUEST=$USER_GUEST
      - PWD_GUEST=$PWD_GUEST
      - USER_ADMIN=$USER_ADMIN
      - PWD_ADMIN=$PWD_ADMIN
      # workspace
      - WORKSPACE_HOME=${WORKSPACE_HOME}
      # outspace
      - OUTSPACE_HOME=${OUTSPACE_HOME}
      # shared volumes
      - SHARED_VOLUMES=$SHARED_VOLUMES
    ports:
      - "${PORT_CORE}:${PORT_CORE}"
    volumes:
      - "conf:/opt/nextflow/conf" # mount config folder: host folder mapped to container folder
      - "workspace:${WORKSPACE_HOME}"
      - "outspace:${OUTSPACE_HOME}"
      - "${SHARED_VOLUME_1}"
    networks:
      - next-launcher-network
    command: [ "sh", "-c", "/opt/nextflow-api/scripts/startup-local.sh mongo" ]

  next-launcher-app:
    image: 'proteomicscnic/next-launcher-app:$NL_VERSION'
    container_name: 'next-launcher-app'
    environment:
      # servers
      - PORT_CORE=$PORT_CORE
      - PORT_APP=$PORT_APP
      - HOST_IP=$HOST_IP
      # workspace
      - WORKSPACE_HOME=${WORKSPACE_HOME}
      # outspace
      - OUTSPACE_HOME=${OUTSPACE_HOME}
      # shared volumes
      - SHARED_VOLUMES=$SHARED_VOLUMES
    ports:
      - "${PORT_APP}:${PORT_APP}"
    volumes:
      - "pipelines:/opt/next-launcher-app/app/public/pipelines" # mount pipeline folder: host folder mapped to container folder
      - "workspace:${WORKSPACE_HOME}"
      - "outspace:${OUTSPACE_HOME}"
      - "${SHARED_VOLUME_1}"
    networks:
      - next-launcher-network
    command: [ "sh", "-c", "cd /opt/next-launcher-app/app && PORT=$PORT_APP  REACT_APP_HOST_IP=$HOST_IP  REACT_APP_PORT_CORE=$PORT_CORE  npm start" ]



volumes:

  conf:
    name: 'conf'
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend/nextflow/conf'

  pipelines:
    name: 'pipelines'
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './frontend/pipelines'

  workspace:
    name: 'workspace'
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:\\next-Launcher\\workspace\\production'

  outspace:
    name: 'outspace'
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:\\next-Launcher\\workspace\\production'

  c:
    name: 'c'
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:\\'



networks:

  next-launcher-network:
