services:

  next-launcher-core:
    image: 'proteomicscnic/next-launcher-core:0.1.0'
    ports:
      - "${PORT_CORE}:${PORT_CORE}"
    environment:
      - PORT_CORE=$PORT_CORE
      - PORT_APP=$PORT_APP
      - HOST_IP=$HOST_IP
    volumes:
      - workspace:/workspace
    networks:
      - app-network
    command: [ "sh", "-c", "/opt/nextflow-api/scripts/startup-local.sh mongo" ]

  next-launcher-app:
    image: 'proteomicscnic/next-launcher-app:0.1.1'
    ports:
      - "${PORT_APP}:${PORT_APP}"
    environment:
      - PORT_CORE=$PORT_CORE
      - PORT_APP=$PORT_APP
      - HOST_IP=$HOST_IP
    volumes:
      - workspace:/workspace
    networks:
      - app-network
    command: [ "sh", "-c", "cd /opt/next-launcher-app/app && PORT=$PORT_APP  REACT_APP_HOST_IP=$HOST_IP  REACT_APP_PORT_CORE=$PORT_CORE  npm start" ]


volumes:

  workspace:
    name: 'workspace'
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:\\next-Launcher\\production'


networks:

  app-network:

